### ISSUE TITLE
Corpus files are not used for anything

### ISSUE THREAD

**Issue by haarg** [briandfoy/pod-perldoc#49]
This dist includes a `corpus` directory, with several pod files in it. But these don't appear to be used for any type of testing or anything else.

Are these only used for manual testing? If so, it would be good to exclude them from the packaged dist by adding them to MANIFEST.SKIP. Or maybe they could just be removed entirely.

The included `perlfunc.pod` file has continually confused people attempting to fix documentation issues in core. Removing it from the shipped distribution would be one solution to that.

**Comment by briandfoy** [comment]
I've just taken over the maintenance of Pod::Perldoc, so I'll look into this. I know it's years old, and it might take me a bit to catch up. 

I think the Makefile.PL says not to index these things, but we shouldn't distribute if they aren't being used in the tests. Or, we should have tests that use them.

**Comment by briandfoy** [comment]
I'm going to write tests that use these files, and I'll figure out something with the perlfunc file too.

**Comment by briandfoy** [comment]
Things to do:

- [ ] don't call it perlfunc.pod. The filename doesn't matter and it confuses other things
- [ ] remove all the files that fetch_pages.pl can grab
- [ ] write a program to convert all the pod to the expected output (and save that)
- [ ] write a test to convert all the files, and compare against the expected versions. For this, we care more about changes over correct output.

**Comment by briandfoy** [comment]
I think I've done most of the work here, and the corpus isn't going to be part of the distro. I haven't merged it yet, but I'm going to track further stuff under #75.
