### ISSUE TITLE
Report bugs here?

### ISSUE THREAD

**Issue by jidanni** [briandfoy/pod-perldoc#50]
https://metacpan.org/pod/Pod::Perldoc says repository is https://github.com/jadeallenx/Pod-Perldoc/ but nobody seems to read the latter.

**Comment by briandfoy** [comment]
Yes, this is the repo for Pod::Perldoc, which hasn't been released since 2017.

**Comment by briandfoy** [comment]
We just transferred the repo to briandfoy/pod-perldoc and I'll have an update out soon.
