### ISSUE TITLE
RT 23471: S<non breaking text> does not work if =encoding is present

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/pod-perldoc#55]
from [jim.avera@gmail.com](https://rt.cpan.org/User/Summary.html?id=584603)

<hr/>

Hi there,

perldoc (using Pod::Perldoc v3.28) folds S<supposedly non breakable text>
if any =encoding statement is present (even =encoding latin1).

STEPS TO REPRODUCE:

1. Save the following demo to foo.pl
2. Resize the terminal to 80 columns
3. perldoc ./foo.pl

RESULTS: The long formula coded in S< ... > is displayed folded, but
should be shown on a single line.  The bug goes away if the =encoding 
directive is removed.

```
#!/usr/bin/perl
1;

=pod

=encoding utf8

=head1 blahblah

Blah blah blah.  The following forumula should not be folded:
S< a + b + c + d + e + f + g + h + i >
but it is.

=cut
```

**Comment by briandfoy** [comment]
I'm trying to reproduce this, but I get the same results with the encoding or without it. I don't disbelieve you and it's probably just that we have different setups. That I can't reproduce it doesn't mean that much for perldoc, which guesses all sorts of things based on local info.

Can you give me some more info? You can add this stuff inline with text, attach files, or whatever. I know this is a lot of stuff, but the problem with `perldoc` issues is that it heavily depends on your local setup:

* what platform and terminal software you use
* `perldoc -h`
* `perl -V`
* `perl -le 'print qq($_: $ENV{$_}) for @ARGV' LANG LC_ALL LC_LANG LESS MANPAGER MANWIDTH MORE PAGER PERLDOC PERLDOC_PAGER PERLDOCDEBUG RTFREADER TERM`
* The perldoc command you ran, with debugging: `env PERLDOCDEBUG=5 perldoc -D ...`
* A hexdump of the output (pipe above command to `hexdump -C`
* what pager you are using (the debug output will show which one perldoc actually chose)
* screenshots—normally I hate these, but in this case I think it might help for you to show me what you expect.

Also, can you explain what you want to happen (or expected to happen). I can imagine a couple of scenarios:

* You want the line to overflow the right margin
* You want the line to have no hard newlines (but soft wrap)
* You want each space to be converted to the right HTML entity (I think this is also broken)
* Something else

<hr/>

The formula portion appears intact on the second line:

```
blahblah
    Blah blah blah. The following forumula should not be folded:
     a + b + c + d + e + f + g + h + i  but it is.
```

If I set the `MANWIDTH` very low, it will wrap (and there are hard newlines in there), but I expect that because I set the `MANWIDTH`:

```
$ export MANWiDTH=30
$ perldoc -o term file
blahblah
    Blah blah blah.
    The following
    forumula should
    not be folded:
    a + b + c + d +
    e + f + g + h +
    i  but it is.
```

If I put extra spaces around the `+` in the formula, those are preserved.

**Comment by jimav** [comment]
Hi Brian.   It's great that you are taking on maint of Pod::Perldoc .   I re-tested and still see the same results, i.e. the presence of "=encoding utf8" allows stuff in S<...> to be folded by perldoc.    I run Ubuntu 23.04 and use gnome-terminal.   I recently switched to use the Cinnamon desktop but the results are the same as they were with Ubuntu's default desktop (gnome3, I think).

Anyway,  the info you asked for is below.

First, here is a copy-paste from my terminal (set to 80 columns wide):
```
[jima /tmp]$ cat foo.pl
#!/usr/bin/perl
1;

=pod

=encoding utf8

=head1 blahblah

Blah blah blah.  The following forumula should not be folded:
S< a + b + c + d + e + f + g + h + i >

=cut
[jima /tmp]$ perldoc foo.pl
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
blahblah
    Blah blah blah. The following forumula should not be folded:  a + b + c
    + d + e + f + g + h + i

[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ cat bar.pl
#!/usr/bin/perl
1;

=pod

=head1 blahblah

Blah blah blah.  The following forumula should not be folded:
S< a + b + c + d + e + f + g + h + i >

=cut
[jima /tmp]$ perldoc bar.pl
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
blahblah
    Blah blah blah. The following forumula should not be folded:
     a + b + c + d + e + f + g + h + i 

[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ : Note that the expression was folded with foo.pl but not bar.pl
[jima /tmp]$ 
[jima /tmp]$ 
[jima /tmp]$ 
```

```
$ perldoc -V
Perldoc v3.2801, under perl v5.036000 for linux

 perl -le 'print qq($_: $ENV{$_}) for @ARGV' LANG LC_ALL LC_LANG LESS MANPAGER MANWIDTH MORE PAGER PERLDOC PERLDOC_PAGER PERLDOCDEBUG RTFREADER TERM
LANG: en_US.UTF-8
LC_ALL: 
LC_LANG: 
LESS: -X -R -q    -M -i --use-color
MANPAGER: 
MANWIDTH: 
MORE: 
PAGER: /home/jima/bin/lesswrapper
PERLDOC: -M Pod::Text::Color
PERLDOC_PAGER: 
PERLDOCDEBUG: 
RTFREADER: 
TERM: xterm-256color
```
[perl-V.txt](https://github.com/briandfoy/pod-perldoc/files/13620644/perl-V.txt)

**Comment by briandfoy** [comment]
This is the best possible outcome: making it someone else's problem :)

Thanks for looking into this.
